"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UuidSchemaDefinition = exports.UrlSchemaDefinition = exports.MongoDBObjectIdSchemaDefinition = exports.IpAddressSchemaDefinition = exports.GeolocationPointSchemaDefinition = exports.EmailAddressSchemaDefinition = exports.DatetimeSchemaDefinition = void 0;
var primitives_1 = require("./primitives");
Object.defineProperty(exports, "DatetimeSchemaDefinition", { enumerable: true, get: function () { return primitives_1.DatetimeSchemaDefinition; } });
Object.defineProperty(exports, "EmailAddressSchemaDefinition", { enumerable: true, get: function () { return primitives_1.EmailAddressSchemaDefinition; } });
Object.defineProperty(exports, "GeolocationPointSchemaDefinition", { enumerable: true, get: function () { return primitives_1.GeolocationPointSchemaDefinition; } });
Object.defineProperty(exports, "IpAddressSchemaDefinition", { enumerable: true, get: function () { return primitives_1.IpAddressSchemaDefinition; } });
Object.defineProperty(exports, "MongoDBObjectIdSchemaDefinition", { enumerable: true, get: function () { return primitives_1.MongoDBObjectIdSchemaDefinition; } });
Object.defineProperty(exports, "UrlSchemaDefinition", { enumerable: true, get: function () { return primitives_1.UrlSchemaDefinition; } });
Object.defineProperty(exports, "UuidSchemaDefinition", { enumerable: true, get: function () { return primitives_1.UuidSchemaDefinition; } });
